require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable

Layout/EndOfLine:
  Enabled: false

Layout/LineLength:
  Max: 144

Metrics/MethodLength:
  Max: 24

Naming/HeredocDelimiterNaming:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

